### ISSUE TITLE
Create a Contributor Guidelines Document

### ISSUE THREAD

**Issue by cyberswat** [drud/community#10]
# What happened (or feature request):
We will be implementing a Contributor License Agreement across the organization that will apply to all repositories.  This brings up the need for a general contributors document that outlines how we would like to engage with contributors.

## What you expected to happen:
A document outlining our philosophy and procedures around contributing should be drafted.

## Anything else do we need to know:
from @rfay 
We're starting to collect some of these("team norms"), unstated but firmly held:
* Approving a PR almost always means having actually tested it live
* The PR creator generally pulls own PR after it's been approved and passed test, when the creator is sure it's the right time.
* Nontrivial PRs normally get two full reviews before pull. Smaller ones may be fine with just one.
* Significant PRs may need to be rebased near the end of their life so that the tests run with all current code (to minimize the potential of breaking master on pull)
* PRs are generally expected to include tests for the new features they're adding, or to prevent relapses on bugs they're fixing.
* The PR template includes a section for a manual testing procedure. Nearly every PR should have explicit instructions on how to do the manual testing.

**Comment by cyberswat** [comment]
It may be worth listing a few examples from other organizations to help people understand the practice.

Here are some example CLA agreements from other software projects you can use to compare:

 - Kubernetes https://github.com/kubernetes/community/blob/master/CLA.md
 - React https://code.facebook.com/cla
 - Apache https://www.apache.org/licenses/#clas
 - GitHub https://cla.github.com/
 - Golang https://golang.org/doc/contribute.html#cla%

**Comment by rickmanelius** [comment]
@cyberswat Can you confirm (with the PR merged) that this is done?
