### ISSUE TITLE
Create a tool that audits our repositories for labels

### ISSUE THREAD

**Issue by cyberswat** [drud/community#13]
## What happened (or feature request):
In our community documentation we outline a strategy for how labels should be used across our repositories.  Manually creating those labels is a tedious process that can quickly become prone to human error.  Please create a tool that can manage labels in accordance with our guidelines.

## What you expected to happen:
* Create a tool that accepts an owner/organization and a reference repository.
* The tool will scan both public and private repositories of the owner and apply labels and colors as they exist in the reference repository.
* The tool should output a report as it processes so that the user can see the results.
* The tool should have a test mode so that the changes can be viewed before executing.
* The tool should be made available to the public under our open source policies.
* Testing coverage should exist for the tool.
* Ensure that our community documentation for labels matches what exists in the community documentation so that the labels being applied by this tool are understood.

## Related source links or issues:
* https://github.com/drud/ghlabel - this is an unfinished, but functional attempt at creating this tool.

**Comment by cyberswat** [comment]
Updating this to remove jenkins integration as that is now documented at https://github.com/drud/aws-infra/issues/58

**Comment by rickmanelius** [comment]
@cyberswat To be clear, does this mean we can close this issue and follow along in the drud/aws-infra#58?

**Comment by cyberswat** [comment]
Just as soon as we hear back from @nmccrory that the items listed here have been addressed.  There is a documentation component in addition to the issue that was merged.

**Comment by nmccrory** [comment]
Sorry for overlooking the docs on this one! @cyberswat

**Comment by nmccrory** [comment]
Docs were taken care of in PR #15. Let's go ahead and close this.

**Comment by cyberswat** [comment]
@nmccrory https://github.com/drud/community/pull/15 isn't merged yet.  We can close this out once that is completed.
