### ISSUE TITLE
Write Up Scrum and Sprint Processes

### ISSUE THREAD

**Issue by dclear** [drud/community#42]
## Feature Description:
Update the community docs to reflect our [current scrum and sprint processes](https://github.com/drud/community/blob/dev/docs/project-management/scrum.md)

## User stories:
As a new member of the DDEV Community, I'd like to have documentation to refer to understand how the team runs its sprints

## Acceptance criteria:
* Migrate and update docs from notion
* Integrate new process recs

## Related links or issues:
https://github.com/drud/community/blob/dev/docs/project-management/scrum.md --> edit directly and it will deploy to https://handbook.ddev.com/en/dev/project-management/scrum/docs/project-management/scrum.md

## Definition of Ready Checklist:

- [x] User-facing feature: provides story or A/C in [Gherkin format](https://cucumber.io/docs/gherkin), or
- [ ] Architectural feature: provides technical A/C
- [ ] Dependencies identified
- [ ] Sized by team

R<sup>Product Owner</sup> A<sup>Scrum Master</sup> C<sup>Eng. Lead</sup> I<sup>Team</sup>

## Definition of Done Checklist:

- [ ] Acceptance Criteria tested and passing
- [ ] Deployed on test environment
- [ ] QA performed & issues resolved
- [ ] Unit test and E2E coverage updated (if applicable)
- [ ] Builds without errors
- [ ] Internal documentation updated (if required)

R<sup>Eng. Lead, Team</sup> A<sup>Scrum Master</sup> CI<sup>Product Owner</sup>

**Comment by dclear** [comment]
@cyberswat : made some grammatical tweaks to scrum process write up at https://github.com/drud/community/commit/c9508e13102ab2fad120bdadc690d325aa025198

**Comment by cyberswat** [comment]
The changes look good. Looking forward to the pull request.

**Comment by dclear** [comment]
merged in https://github.com/drud/handbook/pull/51

**Comment by dclear** [comment]
completed
