### ISSUE TITLE
Consistent application of issue and PR templates and LICENSE across repos

### ISSUE THREAD

**Issue by cyberswat** [drud/community#7]
https://github.com/drud/docker.php7/pull/3 introduced a nice template update for issues and pull requests.  It would be nice to have a tool that would apply those across repositories in a similar fashion to how labels are being managed.  This needs to wait until the label code is committed/reviewed.

**Comment by rfay** [comment]
Also in https://github.com/drud/community/pull/6 here.

**Comment by rfay** [comment]
One of the problems we have is that this drifts over time as our needs change. build-tools has the same problem; the solution there is the [build_update.sh](https://github.com/drud/build-tools/blob/master/build_update.sh) which works, but is a little awkward.  Of course, changing the github templates doesn't actually touch any code or behavior, so it's less sensitive, and I doubt any of us would be concerned with an automatic push of a change.
